project_name: protoc-gen-avro
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    dir: .
    goos:
      - linux
      - darwin
    binary: protoc-gen-avro
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: ikstewa
    name: protoc-gen-avro

archives:
  - id: protoc-gen-avro
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
#brews:
#  -
#    name: global_docker_compose
#    folder: Formula
#    tap:
#      owner: wishabi
#      name: homebrew-flipp
#      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"
#    description: Standardized and centralized Docker compose command
